---
- name: Create docker registry
  community.docker.docker_container:
    name: registry
    image: registry
    ports:
     - "5000:5000"
    restart_policy: always
  when: inventory_hostname in groups['masters']

- name: Write daemon.json
  become: yes
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Remove app folder
  file:
    path: /home/terracloud/laravel
    state: absent

- name: Clone laravel app repo
  ansible.builtin.git:
    repo: https://github.com/EdPaillard/terracloud
    dest: /home/terracloud/laravel
    version: release/k3s

- name: Copy .env
  template:
    src: .env.j2
    dest: /home/terracloud/laravel/sample-app-master/.env

- name: Build terracloud app and push to registry
  community.docker.docker_image:
    build:
      path: /home/terracloud/laravel/sample-app-master
    name: "{{ groups['masters'][0] }}:5000/terracloud-laravel"
    push: true
    source: build
  when: inventory_hostname in groups['masters']

# - name: Start laravel docker-compose
#   become: true
#   community.docker.docker_compose:
#     project_src: /home/terracloud/laravel/
#   register: output

# - name: Show results
#   ansible.builtin.debug:
#     var: output

# - name: Run migrations
#   become: true
#   community.docker.docker_container_exec:
#     container: laravel_app
#     command: "php artisan migrate -q"
#   register: resultmig

# - name: Print stdout
#   ansible.builtin.debug:
#     var: resultmig.stdout

# - name: Run db:seed
#   become: true
#   community.docker.docker_container_exec:
#     container: laravel_app
#     command: "php artisan db:seed -q"
#   register: resultdbs

# - name: Print stdout
#   ansible.builtin.debug:
#     var: resultdbs.stdout

# - name: Run migrations
#   become: yes
#   command: docker exec -it laravel_app php artisan migrate -q

# - name: Run db seed
#   become: yes
#   command: docker exec -it laravel_app php artisan db:seed -q