---
- name: Install apt utilities
  become: yes
  apt:
    pkg:
      - vim
      - curl
      - ca-certificates
      - gnupg
      - python3-pip
      - mysql-server
      - mysql-client
    update_cache: yes

- name: Install pip utilities
  become: yes
  pip:
    name:
      - PyMySQL