version: "3.9"
services:
  web:
    build: .
    container_name: laravel_app
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - "80:80"
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ADMIN_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
