version: "3.9"
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
