all:
  hosts:
    terracloud-vm0.westeurope.cloudapp.azure.com:
      ansible_host: 52.136.232.232
    terracloud-vm1.westeurope.cloudapp.azure.com:
      ansible_host: 52.136.239.154
    terracloud-vm2.westeurope.cloudapp.azure.com:
      ansible_host: 52.136.239.132
  children:
    masters:
      hosts:
        terracloud-vm0.westeurope.cloudapp.azure.com:
    workers:
      hosts:
        terracloud-vm1.westeurope.cloudapp.azure.com:
        terracloud-vm2.westeurope.cloudapp.azure.com:
