name: 'Azure Login'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible requests
      - name: set ansible config secrets
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}
        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > .ansible-vault-password
          mkdir .ssh
          echo "$DO_SSH_KEY" > .ssh/id_digitalocean
          chmod 600 .ssh/id_digitalocean
      - name: run exporters playbook
        env:
          DO_API_KEY: ${{ secrets.DO_API_KEY }}
        run: |
          ansible-playbook -i inventory play.yml